#!/bin/bash -e
echo "Installing gcloud cli"

: ${GCLI_VER:=416.0.0}

if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then
    ARCH="linux-arm"
elif [ "${TARGETPLATFORM}" = "linux/amd64" ]; then
    ARCH="linux-x86_64"
else
    echo "Unknown target platform ${TARGETPLATFORM}"
    exit 1
fi

curl -O "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${GCLI_VER}-${ARCH}.tar.gz"

tar -xf "google-cloud-cli-${GCLI_VER}-${ARCH}.tar.gz"
./google-cloud-sdk/install.sh
rm "google-cloud-cli-${GCLI_VER}-${ARCH}.tar.gz"

