#!/bin/bash -e
echo "Installing terraform"
: "${TERRAFORM_VER:="v1.9.4"}"

git clone -b "${TERRAFORM_VER}"  --depth 1 https://github.com/hashicorp/terraform.git
cd terraform
/usr/local/go/bin/go install
cd .. && rm -rf terraform
