#!/bin/bash -lie
echo "Verifying all tools..."

cdktf --version
cloud-sql-proxy --version
emacs --version
gcloud --version
go version
node --version
pip --version
pipenv --version
psql --version
python --version
terraform version
vim --version

echo  " - OK"
