name: No secrets in commits

# This will be duplicated in all git repos until I find a solution.

on:
  push:

jobs:
  check-no-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: run tartufo
        run: |
          docker run --rm -v "`pwd`:/git" godaddy/tartufo:3.3.1   scan-local-repo /git  
      - name: run gitleaks
        run: |
          docker run --rm -v "`pwd`:/path" zricethezav/gitleaks:v8.15.2 detect --source="/path" -v
